# Generated by Django 2.2 on 2019-04-23 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_path', models.FileField(upload_to='task_storage/', verbose_name='source_json')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskgen.TaskType')),
            ],
        ),
    ]
