# Generated by Django 2.2 on 2019-04-23 22:51

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taskgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('task_id', models.CharField(max_length=200, null=True, verbose_name='task_id')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='taskgen.TaskTree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
