# Generated by Django 2.1.2 on 2019-04-15 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_choisetry_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choisetry',
        ),
    ]
